version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverlessrepo-evb-local"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1axe215vxmn7x"
s3_prefix = "serverlessrepo-evb-local"
region = "eu-west-1"
capabilities = "CAPABILITY_NAMED_IAM"

